//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agriculture_Calender
    {
        public long id { get; set; }
        public string file_name { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public bool active { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
