//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_stats
    {
        public long id { get; set; }
        public string stats { get; set; }
        public string title { get; set; }
        public string icon { get; set; }
        public string text_color { get; set; }
        public string bg_color { get; set; }
        public bool enabled { get; set; }
        public int total { get; set; }
    }
}
