//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public long id { get; set; }
        public long lab_id { get; set; }
        public Nullable<long> user_id { get; set; }
        public Nullable<long> region_id { get; set; }
        public Nullable<System.DateTime> appointment_date { get; set; }
        public Nullable<System.TimeSpan> appointment_time { get; set; }
        public bool is_booked { get; set; }
        public bool is_canceled { get; set; }
        public bool is_sample_collected { get; set; }
        public int no_samples { get; set; }
        public bool is_completed { get; set; }
        public Nullable<long> cancel_by { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual lab lab { get; set; }
        public virtual region region { get; set; }
        public virtual user user { get; set; }
    }
}
