//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class bug_history
    {
        public long id { get; set; }
        public Nullable<long> bug_id { get; set; }
        public string status { get; set; }
        public string msg { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual user user { get; set; }
        public virtual bug_tracker bug_tracker { get; set; }
    }
}
