//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class bug_tracker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bug_tracker()
        {
            this.bug_history = new HashSet<bug_history>();
        }
    
        public long id { get; set; }
        public string msg { get; set; }
        public string image { get; set; }
        public string page { get; set; }
        public string status { get; set; }
        public int type { get; set; }
        public long created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<long> updated_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bug_history> bug_history { get; set; }
        public virtual user user { get; set; }
    }
}
