//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class calldetail
    {
        public long id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> type { get; set; }
        public long user_to { get; set; }
        public long user_from { get; set; }
        public string call_id { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
