//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicAppointment
    {
        public int Id { get; set; }
        public long DoctorId { get; set; }
        public Nullable<long> CustmerId { get; set; }
        public Nullable<int> ClinicId { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public System.TimeSpan AppointmentTime { get; set; }
        public int CallDuration { get; set; }
        public int Status { get; set; }
        public string BookingResone { get; set; }
        public bool IsBooked { get; set; }
        public bool IsCanceled { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<long> UserId { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual user user { get; set; }
    }
}
