//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultationAppointment
    {
        public long Id { get; set; }
        public long consultantId { get; set; }
        public long skillId { get; set; }
        public System.DateTime appointmentDate { get; set; }
        public System.TimeSpan appointmentTime { get; set; }
        public System.DateTime createdAt { get; set; }
        public long createdBy { get; set; }
        public bool isCanceled { get; set; }
        public Nullable<long> canceledBy { get; set; }
        public Nullable<long> callStartBy { get; set; }
        public int callDuration { get; set; }
        public Nullable<System.DateTime> callStartAt { get; set; }
        public string cancelReason { get; set; }
        public string bookingReason { get; set; }
    
        public virtual user userConsultant { get; set; }
        public virtual skill skill { get; set; }
        public virtual user userCallStart { get; set; }
        public virtual user userCancel { get; set; }
        public virtual user userFarmer { get; set; }
    }
}
