//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class consultant_rating
    {
        public long id { get; set; }
        public Nullable<long> consultant_id { get; set; }
        public Nullable<long> user_id { get; set; }
        public string comment { get; set; }
        public Nullable<decimal> rating { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
