//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class currentweathernotificationforCity
    {
        public long id { get; set; }
        public long service_id { get; set; }
        public string link { get; set; }
        public string title { get; set; }
        public long region_id { get; set; }
        public int city_id { get; set; }
        public string message { get; set; }
        public int alert_hazard_id { get; set; }
        public int alert_type_id { get; set; }
        public System.DateTime notification_at { get; set; }
        public Nullable<System.DateTime> from_date { get; set; }
        public Nullable<System.DateTime> to_date { get; set; }
    }
}
