//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class faq
    {
        public long id { get; set; }
        public string question { get; set; }
        public string answer { get; set; }
        public int sort { get; set; }
        public bool active { get; set; }
        public System.DateTime created_at { get; set; }
        public long created_by { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<long> updated_by { get; set; }
    }
}
