//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmVisitMedia
    {
        public long Id { get; set; }
        public string Path { get; set; }
        public string Extention { get; set; }
        public string FileCategory { get; set; }
        public string FileName { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> FarmVisitOrderId { get; set; }
        public Nullable<long> FarmVisitReportId { get; set; }
    
        public virtual FarmVisitOrder FarmVisitOrder { get; set; }
        public virtual FarmVisitReport FarmVisitReport { get; set; }
    }
}
