//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmVisitOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FarmVisitOrder()
        {
            this.FarmVisitReports = new HashSet<FarmVisitReport>();
            this.FarmVisitStatuses = new HashSet<FarmVisitStatus>();
            this.FarmVisitMedias = new HashSet<FarmVisitMedia>();
        }
    
        public long Id { get; set; }
        public string FarmName { get; set; }
        public string Description { get; set; }
        public string PurposeOfVisit { get; set; }
        public long RegionId { get; set; }
        public long CityId { get; set; }
        public string Location { get; set; }
        public string VisitStausId { get; set; }
        public long FarmerId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime VisitDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FarmVisitReport> FarmVisitReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FarmVisitStatus> FarmVisitStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FarmVisitMedia> FarmVisitMedias { get; set; }
    }
}
