//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmVisitStatus
    {
        public long Id { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<long> FarmVisitOrderId { get; set; }
    
        public virtual FarmVisitOrder FarmVisitOrder { get; set; }
    }
}
