//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetLatestProductPrice
    {
        public string product_name { get; set; }
        public string unit { get; set; }
        public string unit_value { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> price_date { get; set; }
        public string category { get; set; }
        public string image { get; set; }
    }
}
