//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_messages
    {
        public long id { get; set; }
        public string message { get; set; }
        public int message_type { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> message_from { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
