//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuidedGuideLog
    {
        public long id { get; set; }
        public long consultantId { get; set; }
        public string guideAlert { get; set; }
        public string cities { get; set; }
        public string skills { get; set; }
        public long regonId { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<int> RecipientsCount { get; set; }
    }
}
