//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class lab_reports
    {
        public long id { get; set; }
        public int lab_id { get; set; }
        public long appointment_id { get; set; }
        public long user_id { get; set; }
        public long region_id { get; set; }
        public System.DateTime collected_date { get; set; }
        public System.DateTime reported_date { get; set; }
        public string collected_by { get; set; }
        public string reported_by { get; set; }
        public string sample_no { get; set; }
        public Nullable<double> soil_electric_conductivity { get; set; }
        public Nullable<double> soil_ph { get; set; }
        public Nullable<double> soil_calcium_carbonate { get; set; }
        public Nullable<double> soil_potasium_ppm { get; set; }
        public Nullable<double> soil_phosphorus_ppm { get; set; }
        public Nullable<double> soil_sand { get; set; }
        public Nullable<double> soil_salt { get; set; }
        public Nullable<double> soil_clay { get; set; }
        public string soil_texture_type { get; set; }
        public string soil_notes { get; set; }
        public string soil_recommendations { get; set; }
        public Nullable<double> water_ph { get; set; }
        public Nullable<double> water_electric_conductivity { get; set; }
        public Nullable<double> water_carbonate { get; set; }
        public Nullable<double> water_chloride { get; set; }
        public Nullable<double> water_salts { get; set; }
        public string water_recommendation { get; set; }
        public string water_notes { get; set; }
        public Nullable<byte> reporttype { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
        public string extra3 { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual user user { get; set; }
    }
}
