//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class market
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public market()
        {
            this.market_products = new HashSet<market_products>();
            this.product_subscribers = new HashSet<product_subscribers>();
            this.user_access = new HashSet<user_access>();
        }
    
        public long id { get; set; }
        public Nullable<long> region_id { get; set; }
        public string marketname { get; set; }
        public string location { get; set; }
        public string address { get; set; }
        public Nullable<System.TimeSpan> open_at { get; set; }
        public Nullable<System.TimeSpan> close_at { get; set; }
        public string contact_person { get; set; }
        public string phone { get; set; }
        public string market_image { get; set; }
        public bool is_active { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<market_products> market_products { get; set; }
        public virtual region region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_subscribers> product_subscribers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_access> user_access { get; set; }
        public virtual user user { get; set; }
    }
}
