//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class market_products
    {
        public long id { get; set; }
        public Nullable<long> market_id { get; set; }
        public Nullable<long> product_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> price_date { get; set; }
        public string unit_value { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual market market { get; set; }
        public virtual product product { get; set; }
    }
}
