//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class medium
    {
        public long id { get; set; }
        public string title { get; set; }
        public string file_name { get; set; }
        public string file_type { get; set; }
        public bool is_internal_file { get; set; }
        public string keywords { get; set; }
        public string description { get; set; }
        public string regions { get; set; }
        public string skills { get; set; }
        public string related_to { get; set; }
        public string seasons { get; set; }
        public bool is_active { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
