//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class msg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public msg()
        {
            this.msg_logs = new HashSet<msg_logs>();
        }
    
        public int id { get; set; }
        public int attention_id { get; set; }
        public long region_id { get; set; }
        public long skill_id { get; set; }
        public string msg1 { get; set; }
    
        public virtual attention attention { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<msg_logs> msg_logs { get; set; }
        public virtual region region { get; set; }
        public virtual skill skill { get; set; }
    }
}
