//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class msg_logs
    {
        public long id { get; set; }
        public int msg_id { get; set; }
        public long user_id { get; set; }
        public System.DateTime send_date { get; set; }
        public string status { get; set; }
    
        public virtual msg msg { get; set; }
        public virtual user user { get; set; }
    }
}
