//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class municipality
    {
        public int id { get; set; }
        public int city_id { get; set; }
        public string name { get; set; }
        public string name_ar { get; set; }
    
        public virtual city city { get; set; }
    }
}
