//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationLog
    {
        public long id { get; set; }
        public int log_type { get; set; }
        public string log_message { get; set; }
        public bool is_processed { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
