//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class otp
    {
        public long id { get; set; }
        public long user_id { get; set; }
        public string otp1 { get; set; }
        public System.DateTime created_at { get; set; }
        public int attempts { get; set; }
    }
}
