//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Page()
        {
            this.roles_permission = new HashSet<roles_permission>();
        }
    
        public int id { get; set; }
        public string PageName { get; set; }
        public string PageName_Ar { get; set; }
        public string Display_Name { get; set; }
        public Nullable<int> Parent_page { get; set; }
        public string Icon { get; set; }
        public Nullable<int> Sort { get; set; }
        public bool should_display { get; set; }
        public bool is_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<roles_permission> roles_permission { get; set; }
    }
}
