//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_subscribers
    {
        public long id { get; set; }
        public Nullable<long> market_id { get; set; }
        public Nullable<long> product_id { get; set; }
        public Nullable<long> user_id { get; set; }
        public int on_increase { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual market market { get; set; }
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
