//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.market_products = new HashSet<market_products>();
            this.product_subscribers = new HashSet<product_subscribers>();
        }
    
        public long id { get; set; }
        public Nullable<long> product_category_id { get; set; }
        public string product_name { get; set; }
        public string product_image { get; set; }
        public Nullable<long> product_type_id { get; set; }
        public string product_origin { get; set; }
        public string slug { get; set; }
        public Nullable<int> unit_id { get; set; }
        public string unit_value { get; set; }
        public bool is_active { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<market_products> market_products { get; set; }
        public virtual product_categories product_categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_subscribers> product_subscribers { get; set; }
        public virtual product_type product_type { get; set; }
        public virtual unit unit { get; set; }
        public virtual user user { get; set; }
    }
}
