//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class qa_answers
    {
        public long id { get; set; }
        public Nullable<long> question_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<long> user_id { get; set; }
        public bool is_approved { get; set; }
        public bool is_verified { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<long> approved_by { get; set; }
        public Nullable<long> verified_by { get; set; }
        public Nullable<System.DateTime> approved_at { get; set; }
        public Nullable<System.DateTime> verified_at { get; set; }
        public Nullable<long> vote_count { get; set; }
    
        public virtual qa_questions qa_questions { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual user user2 { get; set; }
    }
}
