//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class qa_votes
    {
        public long id { get; set; }
        public Nullable<long> user_id { get; set; }
        public Nullable<long> type_id { get; set; }
        public Nullable<bool> type { get; set; }
        public Nullable<bool> is_up_vote { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual user user { get; set; }
    }
}
