//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReefComponentSuggestion
    {
        public int Id { get; set; }
        public string name { get; set; }
        public int ReefComponentId { get; set; }
    
        public virtual ReefComponent ReefComponent { get; set; }
    }
}
