//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempuser
    {
        public string Name { get; set; }
        public string Phone { get; set; }
        public int Phone_Type { get; set; }
        public int Active { get; set; }
        public System.DateTime Date_Created { get; set; }
        public int Temp { get; set; }
    }
}
