//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.appointments = new HashSet<appointment>();
            this.bug_history = new HashSet<bug_history>();
            this.commentsByUsers = new HashSet<commentsByUser>();
            this.commentsByUsers1 = new HashSet<commentsByUser>();
            this.consultant_rating = new HashSet<consultant_rating>();
            this.consultant_rating1 = new HashSet<consultant_rating>();
            this.general_notifications = new HashSet<general_notifications>();
            this.group_user = new HashSet<group_user>();
            this.markets = new HashSet<market>();
            this.msg_logs = new HashSet<msg_logs>();
            this.product_categories = new HashSet<product_categories>();
            this.product_subscribers = new HashSet<product_subscribers>();
            this.products = new HashSet<product>();
            this.qa_answers = new HashSet<qa_answers>();
            this.qa_answers1 = new HashSet<qa_answers>();
            this.qa_answers2 = new HashSet<qa_answers>();
            this.qa_questions = new HashSet<qa_questions>();
            this.qa_questions1 = new HashSet<qa_questions>();
            this.qa_questions2 = new HashSet<qa_questions>();
            this.qa_votes = new HashSet<qa_votes>();
            this.skill_user = new HashSet<skill_user>();
            this.subscribers = new HashSet<subscriber>();
            this.user_access = new HashSet<user_access>();
            this.lab_reports = new HashSet<lab_reports>();
            this.bug_tracker = new HashSet<bug_tracker>();
            this.articles = new HashSet<article>();
            this.Workers = new HashSet<Worker>();
            this.ClinicAppointmentHistories = new HashSet<ClinicAppointmentHistory>();
            this.ClinicAppointments = new HashSet<ClinicAppointment>();
            this.Doctors = new HashSet<Doctor>();
            this.ConsultationAppointments = new HashSet<ConsultationAppointment>();
            this.ConsultationAppointments1 = new HashSet<ConsultationAppointment>();
            this.ConsultationAppointments2 = new HashSet<ConsultationAppointment>();
            this.ConsultationAppointments3 = new HashSet<ConsultationAppointment>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> phone_verified_at { get; set; }
        public long role_id { get; set; }
        public string user_id { get; set; }
        public string password { get; set; }
        public string device_token { get; set; }
        public int app_type { get; set; }
        public long region_id { get; set; }
        public string avatar { get; set; }
        public string firebase_token { get; set; }
        public bool active { get; set; }
        public string country { get; set; }
        public string region { get; set; }
        public string skills { get; set; }
        public string governorate { get; set; }
        public string municipality { get; set; }
        public string linked_in { get; set; }
        public string profile { get; set; }
        public string chatId { get; set; }
        public decimal rating { get; set; }
        public string prefix { get; set; }
        public string last_name { get; set; }
        public string app_ver { get; set; }
        public bool is_online { get; set; }
        public bool is_profile_completed { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string city_code { get; set; }
        public bool is_approved { get; set; }
        public bool is_group_admin { get; set; }
        public bool can_post { get; set; }
        public bool is_weather_notification_enabled { get; set; }
        public bool is_market_notification_enabled { get; set; }
        public System.DateTime last_login_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appointment> appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bug_history> bug_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commentsByUser> commentsByUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commentsByUser> commentsByUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consultant_rating> consultant_rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consultant_rating> consultant_rating1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<general_notifications> general_notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<group_user> group_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<market> markets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<msg_logs> msg_logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_categories> product_categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_subscribers> product_subscribers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_answers> qa_answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_answers> qa_answers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_answers> qa_answers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_questions> qa_questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_questions> qa_questions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_questions> qa_questions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_votes> qa_votes { get; set; }
        public virtual region region1 { get; set; }
        public virtual role role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<skill_user> skill_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subscriber> subscribers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_access> user_access { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lab_reports> lab_reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bug_tracker> bug_tracker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<article> articles { get; set; }
        public virtual user users1 { get; set; }
        public virtual user user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Worker> Workers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClinicAppointmentHistory> ClinicAppointmentHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClinicAppointment> ClinicAppointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor> Doctors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultationAppointment> ConsultationAppointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultationAppointment> ConsultationAppointments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultationAppointment> ConsultationAppointments2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultationAppointment> ConsultationAppointments3 { get; set; }
    }
}
