//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_access
    {
        public long id { get; set; }
        public long userid { get; set; }
        public Nullable<long> labid { get; set; }
        public Nullable<long> marketid { get; set; }
    
        public virtual lab lab { get; set; }
        public virtual market market { get; set; }
        public virtual user user { get; set; }
    }
}
