//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video()
        {
            this.VideoComments = new HashSet<VideoComment>();
            this.VideoLikes = new HashSet<VideoLike>();
        }
    
        public System.Guid Id { get; set; }
        public long VideoCategoryId { get; set; }
        public string Title { get; set; }
        public long UserId { get; set; }
        public string Path { get; set; }
        public string RejectReason { get; set; }
        public long VideoStatusId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<long> VideoCommentId { get; set; }
        public Nullable<long> VideoLikeId { get; set; }
        public Nullable<long> VideoTagId { get; set; }
        public string Extension { get; set; }
        public Nullable<long> RejectedBy { get; set; }
        public Nullable<System.DateTime> RejectedAt { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsHidden { get; set; }
    
        public virtual VideoCategory VideoCategory { get; set; }
        public virtual VideoTag VideoTag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoComment> VideoComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoLike> VideoLikes { get; set; }
    }
}
