//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VideoComment()
        {
            this.CommentsReplies = new HashSet<VideoComment>();
        }
    
        public long Id { get; set; }
        public System.Guid VideoId { get; set; }
        public string Comment { get; set; }
        public long CommentBy { get; set; }
        public System.DateTime CommentReplyAt { get; set; }
        public long CommentReplyBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<long> ParentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoComment> CommentsReplies { get; set; }
        public virtual VideoComment videoComment { get; set; }
        public virtual Video Video { get; set; }
    }
}
