//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class weather_notification
    {
        public long id { get; set; }
        public Nullable<long> notification_class_id { get; set; }
        public string title_ar { get; set; }
        public string title_en { get; set; }
        public string message { get; set; }
        public string link { get; set; }
        public string link_title { get; set; }
        public Nullable<long> region_id { get; set; }
        public string city { get; set; }
        public string season { get; set; }
    
        public virtual notification_class notification_class { get; set; }
        public virtual region region { get; set; }
    }
}
