//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerJob
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public long WorkerId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public long UpdatedBy { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
