//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurshadikCP.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.WorkerExperiences = new HashSet<WorkerExperience>();
            this.WorkerJobs = new HashSet<WorkerJob>();
            this.WorkerNotifications = new HashSet<WorkerNotification>();
        }
    
        public long Id { get; set; }
        public string Phone { get; set; }
        public long IDNumber { get; set; }
        public string Address { get; set; }
        public long CityId { get; set; }
        public bool IsActive { get; set; }
        public bool Isbusy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public long CteatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public long UpdatedBy { get; set; }
        public int NationaltyId { get; set; }
        public long UserId { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int ExpectedSalary { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Nationalty Nationalty { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkerExperience> WorkerExperiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkerJob> WorkerJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkerNotification> WorkerNotifications { get; set; }
    }
}
